const PATH = {
  home: '/',
  login: '/login',
  register: '/register',
  profile: '/profile',
  genres: '/genres',
  comics: '/comics',
  new: '/new-comics',
  top: '/top',
  type: ':type',
  name: ':slug',
  idChapter: ':slug_chapter',
  daily: '/daily',
  weekly: '/weekly',
  monthly: '/monthly',
  chapter: '/chapter',
  follow: '/follow',
  comment: '/comment',
  comments: '/comments',
  recent: '/recent-update-comics',
  recommend: '/recommend-comics',
  popular: '/trending-comics',
  completed: '/completed-comics',
  boy: '/boy-comics',
  girl: '/girl-comics',
  chapters: '/chapters',
  search: '/search',
  download: '/download',
  history: '/history',
  favorite: '/favorite',
  searchSuggest: '/search-suggest'
} as const

export default PATH
